name: 'Setup MSVC Developer Environment'
description: 'Set up MSVC Developer PowerShell environment on Windows'
author: 'Jiaming Yuan'

runs:
  using: 'composite'
  steps:
    - name: Setup MSVC environment
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Map runner.arch to MSVC arch names
        $archMap = @{
          "X64" = "x64"
          "X86" = "x86"
          "ARM64" = "arm64"
          "ARM" = "arm"
        }
        $arch = $archMap["${{ runner.arch }}"]
        if (-not $arch) {
          Write-Error "Unsupported architecture: ${{ runner.arch }}"
          exit 1
        }

        # Host arch can only be x64 or x86
        $hostArch = if ("${{ runner.arch }}" -eq "X86") { "x86" } else { "x64" }

        Write-Host "Runner arch: ${{ runner.arch }}"
        Write-Host "MSVC target arch: $arch"
        Write-Host "MSVC host arch: $hostArch"

        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $vsPath = & $vswhere -latest -property installationPath
        Import-Module "$vsPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=$arch -host_arch=$hostArch"
        # Export environment variables for subsequent steps
        Get-ChildItem env: | ForEach-Object {
          "$($_.Name)=$($_.Value)" >> $env:GITHUB_ENV
        }
