name: 'Setup sccache with GitHub Cache'
description: 'Set up sccache using the rapidsai fork with GitHub Actions cache backend'
author: 'Your Name'

inputs:
  version:
    description: 'Version of sccache to install (e.g., v0.8.2)'
    required: false
    default: 'v0.8.2'
  cache-key-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: 'sccache'

runs:
  using: 'composite'
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux)
            echo "os=unknown-linux-musl" >> $GITHUB_OUTPUT
            ;;
          macOS)
            echo "os=apple-darwin" >> $GITHUB_OUTPUT
            ;;
          Windows)
            echo "os=pc-windows-msvc" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unsupported OS: ${{ runner.os }}"
            exit 1
            ;;
        esac

        case "${{ runner.arch }}" in
          X64)
            echo "arch=x86_64" >> $GITHUB_OUTPUT
            ;;
          ARM64)
            echo "arch=aarch64" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unsupported architecture: ${{ runner.arch }}"
            exit 1
            ;;
        esac

    - name: Download and install sccache
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        ARCH="${{ steps.platform.outputs.arch }}"
        OS="${{ steps.platform.outputs.os }}"

        # Construct download URL for rapidsai fork
        FILENAME="sccache-${VERSION}-${ARCH}-${OS}"
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          FILENAME="${FILENAME}.zip"
        else
          FILENAME="${FILENAME}.tar.gz"
        fi

        URL="https://github.com/rapidsai/sccache/releases/download/${VERSION}/${FILENAME}"
        echo "Downloading sccache from: ${URL}"

        # Create install directory
        INSTALL_DIR="${HOME}/.local/bin"
        mkdir -p "${INSTALL_DIR}"

        # Download and extract
        cd /tmp
        curl -fsSL -o sccache-archive "${URL}"

        if [[ "${{ runner.os }}" == "Windows" ]]; then
          unzip sccache-archive
          mv sccache-${VERSION}-${ARCH}-${OS}/sccache.exe "${INSTALL_DIR}/"
        else
          tar -xzf sccache-archive
          mv sccache-${VERSION}-${ARCH}-${OS}/sccache "${INSTALL_DIR}/"
          chmod +x "${INSTALL_DIR}/sccache"
        fi

        # Add to PATH
        echo "${INSTALL_DIR}" >> $GITHUB_PATH

        # Verify installation
        "${INSTALL_DIR}/sccache" --version

    - name: Export GitHub Actions cache environment
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Configure sccache for GitHub Actions cache
      shell: bash
      run: |
        # Enable GitHub Actions cache backend
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

        # Set cache key prefix for organization
        echo "SCCACHE_GHA_CACHE_KEY_PREFIX=${{ inputs.cache-key-prefix }}" >> $GITHUB_ENV

        # Configure CMake to use sccache as compiler launcher
        echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

    - name: Start sccache server
      shell: bash
      run: |
        sccache --start-server || true
        echo "::group::sccache initial stats"
        sccache --show-stats
        echo "::endgroup::"

branding:
  icon: 'zap'
  color: 'orange'
