name: 'Cleanup sccache'
description: 'Stop sccache server and display statistics'
author: 'Your Name'

runs:
  using: 'composite'
  steps:
    - name: Show sccache statistics
      shell: bash
      run: |
        echo "::group::sccache final stats"
        sccache --show-stats || true
        echo "::endgroup::"

    - name: Stop sccache server
      shell: bash
      run: |
        sccache --stop-server || true

branding:
  icon: 'zap'
  color: 'orange'
